商品削除機能
noncover222kdy/freemarket_sample_47b pull request #81
Opened 2019-04-14 11:22 UTC by aki800

#WHAT
商品削除機能を実装

#WHY
商品を削除できるようにするため

2019-04-14 11:58 UTC, ghost requested changes

2019-04-14 11:58 UTC, hiroki5123 commented on app/controllers/items_controller.rb
> +    if item.update(item_params)
32行目と33行目で同じこと書いてませんか？

2019-04-14 11:58 UTC, hiroki5123 commented on app/controllers/items_controller.rb
> +    item.destroy
destroyできなかったときのエラーハンドリングを書きましょう

2019-04-14 11:58 UTC, hiroki5123 commented on app/views/items/destroy.html.haml
> +          %a{:href => "#"}
link_toで仮置きしておきましょう

2019-04-14 11:58 UTC, hiroki5123 commented on app/views/items/exhibitshow.html.haml
> +          %a{"data-slide-index" => "0", href: ""}
こちらも

2019-04-14 11:58 UTC, hiroki5123 commented on app/views/users/exhibitindex.html.haml
> +      - @items.each do |item|
renderのコレクションオプションを使いましょう

2019-04-14 11:59 UTC, hiroki5123 commented
そのビュー崩れはいつ修正するんでしょうか？

2019-04-14 12:02 UTC, ato-tech approved these changes

2019-04-14 12:02 UTC, ato-tech commented on app/assets/stylesheets/item_exhibitindex.scss
> +  &_interval {
この場合BEM記法では__（ハイフン二つ）になります。細かいですが、全体をBEMに修正してください。

2019-04-14 12:02 UTC, ato-tech commented on app/assets/stylesheets/item_exhibitindex.scss
> +        width: calc(700px / 3);
SASSは演算できますのでこの場合は700px / 3のみで大丈夫です。
calcを使うのは%とpxなど異なる単位の計算のみです。

2019-04-14 12:02 UTC, ato-tech commented on app/controllers/items_controller.rb
> +    item = Item.find(params[:id])
編集機能はこのプルリクエストには含まれないため、削除しましょう。

2019-04-14 12:02 UTC, ato-tech commented on app/controllers/items_controller.rb
> +  def exhibitshow
こちらはなんでしょう？基本的にrailsの7つのアクションで実装するようにしましょう。

2019-04-14 12:02 UTC, ato-tech commented on app/views/items/destroy.html.haml
> += render :partial => "layouts/main-header"
ハッシュロケットはやめましょう。

2019-04-14 12:02 UTC, ato-tech commented on app/views/items/destroy.html.haml
> +          %a{:href => "#"}
リンク先は仮置きでかまいませんので、link_toを使いましょう。

2019-04-14 12:04 UTC, aki800 commented on app/controllers/items_controller.rb
> +    if item.update(item_params)
32行目を消去しました。

2019-04-14 12:21 UTC, aki800 commented on app/views/items/destroy.html.haml
> +          %a{:href => "#"}
全ての %a{:href => "#"}をlink_toで仮置きしました。

2019-04-14 12:31 UTC, aki800 commented on app/views/items/exhibitshow.html.haml
> +          %a{"data-slide-index" => "0", href: ""}
link_toで仮置きしました。

2019-04-15 02:48 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +    else item.destroy
rubyでは、elseに対して条件式を付与することはできませんし、ifと重複しているのですが…

2019-04-15 02:55 UTC, aki800 commented
rubyでは、elseに対して条件式を付与することはできませんし、ifと重複しているのですが…
↓
items_controllerのdestroyアクションの条件分岐の記述を修正しました。
(メンターさんのコメントを誤って消してしまいました。すみません。。）

2019-04-15 02:57 UTC, miyagit commented on app/controllers/items_controller.rb
>        redirect_to controller: :users, action: :index
redirect_to users_pathですかね？？

2019-04-15 03:03 UTC, aki800 commented
items_controllerのdestroyアクションの、リダイレクト先のパスの書き方を変更しました。

2019-04-15 03:10 UTC, kuroko918 commented on app/controllers/items_controller.rb
> +      redirect_to controller: :items, action: :index
こちらもprefixを使用して記述しましょう！

2019-04-15 03:17 UTC, kuroko918 commented
一旦いいかと思います！
マージして次へ進んでください！

2019-04-15 03:18 UTC, merged